# This is a GitHub actions workflow for wgrib2.
#
# This builds the develop branch on MacOS.
#
# Alyson Stahl, 2/11/2025
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      #LD_LIBRARY_PATH: "/Users/runner/work/wgrib2/wgrib2/nceplibs/jasper/lib/"
    strategy:
      fail-fast: false
      matrix:
        ccompiler: [gcc-12, gcc-14, clang]
        jasper-version: [4.0.0]
        #openmp: [ ON, OFF ]
        #sharedlib: [ ON, OFF ]

    steps:
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        brew install libpng jpeg-turbo openjpeg libaec libomp

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        g2c-version: develop
        g2c-cmake-args: -DUSE_Jasper=ON
        jasper-version: version-${{ matrix.jasper-version }}
        ip-version: develop

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: wgrib2

    - name: build
      run: |
        cd wgrib2
        mkdir build
        cd build
        export CFLAGS='-I/Users/runner/work/wgrib2/wgrib2/nceplibs/NCEPLIBS-g2c/include'
        #cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip" .. -DUSE_AEC=OFF -DUSE_PNG=ON -DUSE_JASPER=ON -DBUILD_SHARED_LIB=${{matrix.sharedlib}} -DMAKE_FTN_API=ON -DUSE_OPENMP=${{matrix.openmp}}
        cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/jasper/lib;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip" .. -DBUILD_LIB=OFF -DBUILD_SHARED_LIB=OFF -DUSE_PNG=ON -DUSE_AEC=ON -DUSE_JASPER=ON
        make VERBOSE=1
        ctest --verbose --output-on-failure --rerun-failed